// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using gevs_api.Data;

#nullable disable

namespace gevs_api.Core.Migrations
{
    [DbContext(typeof(GevsDbContext))]
    [Migration("20240110161225_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("gevs_api.Domain.Candidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConstituencyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("uuid");

                    b.Property<int>("VoteCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConstituencyId");

                    b.HasIndex("PartyId");

                    b.ToTable("Candidates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4b169931-e458-4650-b463-3f7b126ff95c"),
                            ConstituencyId = new Guid("2601cd67-9625-4c13-9767-593eb79366fd"),
                            Name = "candidate 1",
                            PartyId = new Guid("9e188e46-ed6d-4c12-9074-1decd992a388"),
                            VoteCount = 4
                        },
                        new
                        {
                            Id = new Guid("87402645-7a3f-4c2f-904b-5475627e12bd"),
                            ConstituencyId = new Guid("2601cd67-9625-4c13-9767-593eb79366fd"),
                            Name = "candidate 2",
                            PartyId = new Guid("9e188e46-ed6d-4c12-9074-1decd992a388"),
                            VoteCount = 2
                        },
                        new
                        {
                            Id = new Guid("588759e7-4bd2-4a77-bbe9-2fb39f9eb478"),
                            ConstituencyId = new Guid("2601cd67-9625-4c13-9767-593eb79366fd"),
                            Name = "candidate 3",
                            PartyId = new Guid("9e188e46-ed6d-4c12-9074-1decd992a388"),
                            VoteCount = 1
                        });
                });

            modelBuilder.Entity("gevs_api.Domain.CandidateResult", b =>
                {
                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Party")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Vote")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("CandidateResults");
                });

            modelBuilder.Entity("gevs_api.Domain.Constituency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Constituencies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dfe5185f-da46-4133-9032-7aa3b8550dcb"),
                            Name = "Shangri-la-Town"
                        },
                        new
                        {
                            Id = new Guid("2601cd67-9625-4c13-9767-593eb79366fd"),
                            Name = "Northern-Kunlun-Mountain"
                        },
                        new
                        {
                            Id = new Guid("577ecc28-a621-417a-aba9-10e82f6a791a"),
                            Name = "Western-Shangri-la"
                        },
                        new
                        {
                            Id = new Guid("9c91e290-c10e-4c77-b1b5-eef3de263c5b"),
                            Name = "Naboo-Vallery"
                        },
                        new
                        {
                            Id = new Guid("277b8634-156b-447c-9042-c7359480b0d2"),
                            Name = "New-Felucia"
                        });
                });

            modelBuilder.Entity("gevs_api.Domain.Election", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ongoing")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Elections");

                    b.HasData(
                        new
                        {
                            Id = new Guid("967939fa-3c70-418d-a8ba-a06748bab46e"),
                            Ongoing = false
                        });
                });

            modelBuilder.Entity("gevs_api.Domain.Party", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Parties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("483f1c77-2f20-4d6c-b1e1-1e0d48509aa5"),
                            Name = "Red Party"
                        },
                        new
                        {
                            Id = new Guid("6d41c47b-407b-4b8d-bb54-7e4190fcd5ee"),
                            Name = "Blue Party"
                        },
                        new
                        {
                            Id = new Guid("9e188e46-ed6d-4c12-9074-1decd992a388"),
                            Name = "Yellow Party"
                        },
                        new
                        {
                            Id = new Guid("4ff82a3a-a7b7-4eeb-8938-74a86209181d"),
                            Name = "Independent"
                        });
                });

            modelBuilder.Entity("gevs_api.Domain.Candidate", b =>
                {
                    b.HasOne("gevs_api.Domain.Constituency", "Constituency")
                        .WithMany()
                        .HasForeignKey("ConstituencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("gevs_api.Domain.Party", "Party")
                        .WithMany()
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Constituency");

                    b.Navigation("Party");
                });
#pragma warning restore 612, 618
        }
    }
}
