// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using gevs_api.Data;

#nullable disable

namespace gevs_api.Core.Migrations
{
    [DbContext(typeof(GevsDbContext))]
    [Migration("20240110171824_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("gevs_api.Domain.Candidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConstituencyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("uuid");

                    b.Property<int>("VoteCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConstituencyId");

                    b.HasIndex("PartyId");

                    b.ToTable("Candidates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ac4ce7eb-669b-4aa0-aa2a-67c74d444770"),
                            ConstituencyId = new Guid("0d351d87-973b-49f3-a457-3a766d610527"),
                            Name = "candidate 1",
                            PartyId = new Guid("1d13e53f-c615-415a-a0d2-4a85f6cbbf31"),
                            VoteCount = 4
                        },
                        new
                        {
                            Id = new Guid("21c132f6-e949-4e25-9ef4-199020bded58"),
                            ConstituencyId = new Guid("0d351d87-973b-49f3-a457-3a766d610527"),
                            Name = "candidate 2",
                            PartyId = new Guid("8d86cc06-d8e8-4d45-805e-bc31d3737903"),
                            VoteCount = 2
                        },
                        new
                        {
                            Id = new Guid("78e8a852-7d7a-4e9b-9b8a-f8472a7bf75a"),
                            ConstituencyId = new Guid("0d351d87-973b-49f3-a457-3a766d610527"),
                            Name = "candidate 3",
                            PartyId = new Guid("9384b241-49f8-4cb9-a7da-6b527bf592dc"),
                            VoteCount = 1
                        });
                });

            modelBuilder.Entity("gevs_api.Domain.CandidateResult", b =>
                {
                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Party")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Vote")
                        .HasColumnType("integer");

                    b.ToTable("CandidateResults");
                });

            modelBuilder.Entity("gevs_api.Domain.Constituency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Constituencies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5867da0d-560e-4f3e-b7b7-29a953e13855"),
                            Name = "Shangri-la-Town"
                        },
                        new
                        {
                            Id = new Guid("0d351d87-973b-49f3-a457-3a766d610527"),
                            Name = "Northern-Kunlun-Mountain"
                        },
                        new
                        {
                            Id = new Guid("95cd3ae7-024a-4414-b2ca-6b577bbc44fc"),
                            Name = "Western-Shangri-la"
                        },
                        new
                        {
                            Id = new Guid("3a9b3651-5e8b-4e5d-acaf-4458ce1c9817"),
                            Name = "Naboo-Vallery"
                        },
                        new
                        {
                            Id = new Guid("2139d8e8-6c6f-4236-90ef-371ccafd0d5f"),
                            Name = "New-Felucia"
                        });
                });

            modelBuilder.Entity("gevs_api.Domain.Election", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ongoing")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Elections");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8dd4041f-8a4c-4479-8a67-b591d412098b"),
                            Ongoing = false
                        });
                });

            modelBuilder.Entity("gevs_api.Domain.Party", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Parties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1d13e53f-c615-415a-a0d2-4a85f6cbbf31"),
                            Name = "Red Party"
                        },
                        new
                        {
                            Id = new Guid("8d86cc06-d8e8-4d45-805e-bc31d3737903"),
                            Name = "Blue Party"
                        },
                        new
                        {
                            Id = new Guid("9384b241-49f8-4cb9-a7da-6b527bf592dc"),
                            Name = "Yellow Party"
                        },
                        new
                        {
                            Id = new Guid("f7329878-3664-4255-be4b-b2f6950590d6"),
                            Name = "Independent"
                        });
                });

            modelBuilder.Entity("gevs_api.Domain.Candidate", b =>
                {
                    b.HasOne("gevs_api.Domain.Constituency", "Constituency")
                        .WithMany()
                        .HasForeignKey("ConstituencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("gevs_api.Domain.Party", "Party")
                        .WithMany()
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Constituency");

                    b.Navigation("Party");
                });
#pragma warning restore 612, 618
        }
    }
}
