// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using gevs_api.Data;

#nullable disable

namespace gevs_api.Core.Migrations
{
    [DbContext(typeof(GevsDbContext))]
    partial class GevsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("gevs_api.Domain.Candidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConstituencyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("uuid");

                    b.Property<int>("VoteCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Candidates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ea9c4bcf-27cd-4eca-b273-de8ac7192211"),
                            ConstituencyId = new Guid("dbe30a0a-0e77-4f20-b4f2-cf894d60fedc"),
                            Name = "candidate 1",
                            PartyId = new Guid("b8156548-34b8-4b3a-bbaa-be1c7bd9c52f"),
                            VoteCount = 4
                        },
                        new
                        {
                            Id = new Guid("5b45bdeb-e6f8-4d18-8704-495115a801c3"),
                            ConstituencyId = new Guid("dbe30a0a-0e77-4f20-b4f2-cf894d60fedc"),
                            Name = "candidate 2",
                            PartyId = new Guid("6eb20bce-be7e-4089-8022-25022f6168b2"),
                            VoteCount = 2
                        },
                        new
                        {
                            Id = new Guid("e56f7fc2-6d2d-4bce-96fd-9fd7d797d3bb"),
                            ConstituencyId = new Guid("dbe30a0a-0e77-4f20-b4f2-cf894d60fedc"),
                            Name = "candidate 3",
                            PartyId = new Guid("72af90b0-e398-40ea-9b48-2d4d4957e0c5"),
                            VoteCount = 1
                        },
                        new
                        {
                            Id = new Guid("342043c5-9256-435c-876c-56f52d874216"),
                            ConstituencyId = new Guid("c36d75a7-7056-4efb-ae23-164933dd19bc"),
                            Name = "candidate 1",
                            PartyId = new Guid("b8156548-34b8-4b3a-bbaa-be1c7bd9c52f"),
                            VoteCount = 4
                        },
                        new
                        {
                            Id = new Guid("e33f560e-950d-4cd8-859d-87417ac89217"),
                            ConstituencyId = new Guid("c36d75a7-7056-4efb-ae23-164933dd19bc"),
                            Name = "candidate 2",
                            PartyId = new Guid("6eb20bce-be7e-4089-8022-25022f6168b2"),
                            VoteCount = 3
                        },
                        new
                        {
                            Id = new Guid("3f974bdc-e458-4626-96dc-399f75a80873"),
                            ConstituencyId = new Guid("c36d75a7-7056-4efb-ae23-164933dd19bc"),
                            Name = "candidate 3",
                            PartyId = new Guid("72af90b0-e398-40ea-9b48-2d4d4957e0c5"),
                            VoteCount = 1
                        },
                        new
                        {
                            Id = new Guid("a9a26ef0-bc54-4af7-8b9b-0708bf5d98e1"),
                            ConstituencyId = new Guid("74c462e3-2226-4e97-857e-b0346c4c990d"),
                            Name = "candidate 1",
                            PartyId = new Guid("e47fd3f6-722d-4f99-b05e-c220b664ce84"),
                            VoteCount = 5
                        },
                        new
                        {
                            Id = new Guid("2c31569c-8471-41fe-b084-b11fc137acc6"),
                            ConstituencyId = new Guid("74c462e3-2226-4e97-857e-b0346c4c990d"),
                            Name = "candidate 2",
                            PartyId = new Guid("6eb20bce-be7e-4089-8022-25022f6168b2"),
                            VoteCount = 2
                        },
                        new
                        {
                            Id = new Guid("d99ef851-0bfe-43bf-83e2-fa8961553ad2"),
                            ConstituencyId = new Guid("74c462e3-2226-4e97-857e-b0346c4c990d"),
                            Name = "candidate 3",
                            PartyId = new Guid("72af90b0-e398-40ea-9b48-2d4d4957e0c5"),
                            VoteCount = 1
                        },
                        new
                        {
                            Id = new Guid("406e17ec-2535-4bb2-8c43-d859a906cae1"),
                            ConstituencyId = new Guid("5c2fccaf-0a2f-48fa-8e04-909a61b9f2ee"),
                            Name = "candidate 1",
                            PartyId = new Guid("b8156548-34b8-4b3a-bbaa-be1c7bd9c52f"),
                            VoteCount = 2
                        },
                        new
                        {
                            Id = new Guid("fdc3665a-00b5-4df7-968f-5e036f56bef6"),
                            ConstituencyId = new Guid("5c2fccaf-0a2f-48fa-8e04-909a61b9f2ee"),
                            Name = "candidate 2",
                            PartyId = new Guid("6eb20bce-be7e-4089-8022-25022f6168b2"),
                            VoteCount = 10
                        },
                        new
                        {
                            Id = new Guid("ba5de2c2-f995-4099-8ab2-7ce4c54e992f"),
                            ConstituencyId = new Guid("5c2fccaf-0a2f-48fa-8e04-909a61b9f2ee"),
                            Name = "candidate 3",
                            PartyId = new Guid("72af90b0-e398-40ea-9b48-2d4d4957e0c5"),
                            VoteCount = 1
                        },
                        new
                        {
                            Id = new Guid("8a6f6e09-bbc7-4c2f-aa76-037e443aa3b9"),
                            ConstituencyId = new Guid("d886a89e-5dd2-4981-921e-ee614c2db184"),
                            Name = "candidate 1",
                            PartyId = new Guid("b8156548-34b8-4b3a-bbaa-be1c7bd9c52f"),
                            VoteCount = 2
                        },
                        new
                        {
                            Id = new Guid("ac94c03a-9579-4ad9-8bd4-e62026ab8084"),
                            ConstituencyId = new Guid("d886a89e-5dd2-4981-921e-ee614c2db184"),
                            Name = "candidate 2",
                            PartyId = new Guid("6eb20bce-be7e-4089-8022-25022f6168b2"),
                            VoteCount = 10
                        },
                        new
                        {
                            Id = new Guid("49a00f1e-c10f-48eb-9d1c-ded7920eea50"),
                            ConstituencyId = new Guid("d886a89e-5dd2-4981-921e-ee614c2db184"),
                            Name = "candidate 3",
                            PartyId = new Guid("72af90b0-e398-40ea-9b48-2d4d4957e0c5"),
                            VoteCount = 6
                        });
                });

            modelBuilder.Entity("gevs_api.Domain.CandidateResult", b =>
                {
                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Party")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Vote")
                        .HasColumnType("integer");

                    b.ToTable("CandidateResults");
                });

            modelBuilder.Entity("gevs_api.Domain.Constituency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Constituencies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c36d75a7-7056-4efb-ae23-164933dd19bc"),
                            Name = "Shangri-la-Town"
                        },
                        new
                        {
                            Id = new Guid("dbe30a0a-0e77-4f20-b4f2-cf894d60fedc"),
                            Name = "Northern-Kunlun-Mountain"
                        },
                        new
                        {
                            Id = new Guid("74c462e3-2226-4e97-857e-b0346c4c990d"),
                            Name = "Western-Shangri-la"
                        },
                        new
                        {
                            Id = new Guid("5c2fccaf-0a2f-48fa-8e04-909a61b9f2ee"),
                            Name = "Naboo-Vallery"
                        },
                        new
                        {
                            Id = new Guid("d886a89e-5dd2-4981-921e-ee614c2db184"),
                            Name = "New-Felucia"
                        });
                });

            modelBuilder.Entity("gevs_api.Domain.Election", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ongoing")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Elections");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2537e525-ef6b-447e-90a5-5332b7c56716"),
                            Ongoing = false
                        });
                });

            modelBuilder.Entity("gevs_api.Domain.Party", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Parties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b8156548-34b8-4b3a-bbaa-be1c7bd9c52f"),
                            Name = "Red Party"
                        },
                        new
                        {
                            Id = new Guid("6eb20bce-be7e-4089-8022-25022f6168b2"),
                            Name = "Blue Party"
                        },
                        new
                        {
                            Id = new Guid("72af90b0-e398-40ea-9b48-2d4d4957e0c5"),
                            Name = "Yellow Party"
                        },
                        new
                        {
                            Id = new Guid("e47fd3f6-722d-4f99-b05e-c220b664ce84"),
                            Name = "Independent"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
