// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using gevs_api.Data;

#nullable disable

namespace gevs_api.Core.Migrations
{
    [DbContext(typeof(GevsDbContext))]
    [Migration("20240114212319_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("gevs_api.Domain.Candidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConstituencyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("uuid");

                    b.Property<int>("VoteCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Candidates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7f7f340b-f012-4930-857d-10fd46c7faa1"),
                            ConstituencyId = new Guid("85ce0a34-08be-4032-85e7-ef08224a4207"),
                            Name = "candidate 1",
                            PartyId = new Guid("ef4264d7-aa9d-4476-ab43-225f82495cfa"),
                            VoteCount = 4
                        },
                        new
                        {
                            Id = new Guid("e0ba1560-e696-41ab-9807-f84b11e31382"),
                            ConstituencyId = new Guid("85ce0a34-08be-4032-85e7-ef08224a4207"),
                            Name = "candidate 2",
                            PartyId = new Guid("41d851f8-5e79-4edf-9d56-79ef517ab8ca"),
                            VoteCount = 2
                        },
                        new
                        {
                            Id = new Guid("3b476bf9-ce36-45e9-a8c1-971ec7f83d0f"),
                            ConstituencyId = new Guid("85ce0a34-08be-4032-85e7-ef08224a4207"),
                            Name = "candidate 3",
                            PartyId = new Guid("d74bc2eb-53ed-4001-a9bf-dd34ea5f4636"),
                            VoteCount = 1
                        },
                        new
                        {
                            Id = new Guid("eff52ea8-1da1-4eaa-a110-723aade28ada"),
                            ConstituencyId = new Guid("c6d95402-0669-43df-892f-0c0542879e19"),
                            Name = "candidate 1",
                            PartyId = new Guid("ef4264d7-aa9d-4476-ab43-225f82495cfa"),
                            VoteCount = 4
                        },
                        new
                        {
                            Id = new Guid("1315993d-a94b-4410-a269-80bb91414988"),
                            ConstituencyId = new Guid("c6d95402-0669-43df-892f-0c0542879e19"),
                            Name = "candidate 2",
                            PartyId = new Guid("41d851f8-5e79-4edf-9d56-79ef517ab8ca"),
                            VoteCount = 2
                        },
                        new
                        {
                            Id = new Guid("cfb67c92-20c1-4984-8478-5506aeae3973"),
                            ConstituencyId = new Guid("c6d95402-0669-43df-892f-0c0542879e19"),
                            Name = "candidate 3",
                            PartyId = new Guid("d74bc2eb-53ed-4001-a9bf-dd34ea5f4636"),
                            VoteCount = 1
                        },
                        new
                        {
                            Id = new Guid("160c5591-5abb-4432-9695-d885907bebf3"),
                            ConstituencyId = new Guid("914fc076-9d45-4802-bcc5-1697a5b46e82"),
                            Name = "candidate 1",
                            PartyId = new Guid("60a58d3b-acc0-4022-ad5a-6e33e21d5a6d"),
                            VoteCount = 0
                        },
                        new
                        {
                            Id = new Guid("754c3e8c-0cf5-4574-9cc4-283281336e23"),
                            ConstituencyId = new Guid("914fc076-9d45-4802-bcc5-1697a5b46e82"),
                            Name = "candidate 2",
                            PartyId = new Guid("41d851f8-5e79-4edf-9d56-79ef517ab8ca"),
                            VoteCount = 4
                        },
                        new
                        {
                            Id = new Guid("20cf66cc-1f03-4068-908d-17a4f3e90076"),
                            ConstituencyId = new Guid("914fc076-9d45-4802-bcc5-1697a5b46e82"),
                            Name = "candidate 3",
                            PartyId = new Guid("ef4264d7-aa9d-4476-ab43-225f82495cfa"),
                            VoteCount = 2
                        },
                        new
                        {
                            Id = new Guid("591f7df8-6220-4469-8f33-323708566a1f"),
                            ConstituencyId = new Guid("ddbe8b38-9967-4642-af8f-48ed6d6d9bca"),
                            Name = "candidate 1",
                            PartyId = new Guid("ef4264d7-aa9d-4476-ab43-225f82495cfa"),
                            VoteCount = 3
                        },
                        new
                        {
                            Id = new Guid("bf6b722f-c8cb-488f-a765-b7fca7c2e5a6"),
                            ConstituencyId = new Guid("ddbe8b38-9967-4642-af8f-48ed6d6d9bca"),
                            Name = "candidate 2",
                            PartyId = new Guid("41d851f8-5e79-4edf-9d56-79ef517ab8ca"),
                            VoteCount = 0
                        },
                        new
                        {
                            Id = new Guid("81c6b534-5ba9-446e-a817-338b9ed91eca"),
                            ConstituencyId = new Guid("ddbe8b38-9967-4642-af8f-48ed6d6d9bca"),
                            Name = "candidate 3",
                            PartyId = new Guid("d74bc2eb-53ed-4001-a9bf-dd34ea5f4636"),
                            VoteCount = 1
                        },
                        new
                        {
                            Id = new Guid("796bf78c-a716-4874-8b20-2bb106f51e74"),
                            ConstituencyId = new Guid("664e1e29-dde9-4439-b871-386e23ca1c4f"),
                            Name = "candidate 1",
                            PartyId = new Guid("ef4264d7-aa9d-4476-ab43-225f82495cfa"),
                            VoteCount = 2
                        },
                        new
                        {
                            Id = new Guid("1df90766-8e94-4678-a9b8-6cd85765710a"),
                            ConstituencyId = new Guid("664e1e29-dde9-4439-b871-386e23ca1c4f"),
                            Name = "candidate 2",
                            PartyId = new Guid("41d851f8-5e79-4edf-9d56-79ef517ab8ca"),
                            VoteCount = 0
                        },
                        new
                        {
                            Id = new Guid("56e4fe23-cd99-40b0-9463-86083cc7aeba"),
                            ConstituencyId = new Guid("664e1e29-dde9-4439-b871-386e23ca1c4f"),
                            Name = "candidate 3",
                            PartyId = new Guid("d74bc2eb-53ed-4001-a9bf-dd34ea5f4636"),
                            VoteCount = 6
                        });
                });

            modelBuilder.Entity("gevs_api.Domain.CandidateResult", b =>
                {
                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Party")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Vote")
                        .HasColumnType("integer");

                    b.ToTable("CandidateResults");
                });

            modelBuilder.Entity("gevs_api.Domain.Constituency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Constituencies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c6d95402-0669-43df-892f-0c0542879e19"),
                            Name = "Shangri-la-Town"
                        },
                        new
                        {
                            Id = new Guid("85ce0a34-08be-4032-85e7-ef08224a4207"),
                            Name = "Northern-Kunlun-Mountain"
                        },
                        new
                        {
                            Id = new Guid("914fc076-9d45-4802-bcc5-1697a5b46e82"),
                            Name = "Western-Shangri-la"
                        },
                        new
                        {
                            Id = new Guid("ddbe8b38-9967-4642-af8f-48ed6d6d9bca"),
                            Name = "Naboo-Vallery"
                        },
                        new
                        {
                            Id = new Guid("664e1e29-dde9-4439-b871-386e23ca1c4f"),
                            Name = "New-Felucia"
                        });
                });

            modelBuilder.Entity("gevs_api.Domain.Election", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ongoing")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Elections");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0c2cd979-8dd6-4993-a0ad-beb3d892592e"),
                            Ongoing = false
                        });
                });

            modelBuilder.Entity("gevs_api.Domain.Party", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Parties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ef4264d7-aa9d-4476-ab43-225f82495cfa"),
                            Name = "Red Party"
                        },
                        new
                        {
                            Id = new Guid("41d851f8-5e79-4edf-9d56-79ef517ab8ca"),
                            Name = "Blue Party"
                        },
                        new
                        {
                            Id = new Guid("d74bc2eb-53ed-4001-a9bf-dd34ea5f4636"),
                            Name = "Yellow Party"
                        },
                        new
                        {
                            Id = new Guid("60a58d3b-acc0-4022-ad5a-6e33e21d5a6d"),
                            Name = "Independent"
                        });
                });

            modelBuilder.Entity("gevs_api.Domain.VoteHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<bool>("HasVoted")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("VoteHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
