// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using gevs_api.Data;

#nullable disable

namespace gevs_api.Core.Migrations
{
    [DbContext(typeof(GevsDbContext))]
    [Migration("20240111170651_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("gevs_api.Domain.Candidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConstituencyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("uuid");

                    b.Property<int>("VoteCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Candidates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7d7d4a4b-051d-4d07-89e8-a8ab41016b04"),
                            ConstituencyId = new Guid("db23f0a0-5ea0-450a-8d25-6afe3a8db280"),
                            Name = "candidate 1",
                            PartyId = new Guid("22e5f6ea-ee2f-40d5-99ce-f48a18b87b95"),
                            VoteCount = 4
                        },
                        new
                        {
                            Id = new Guid("7f582c16-0268-4db9-aeda-43fdd874e0d1"),
                            ConstituencyId = new Guid("db23f0a0-5ea0-450a-8d25-6afe3a8db280"),
                            Name = "candidate 2",
                            PartyId = new Guid("dbb4d60a-e99d-4ea0-9451-c545266db2ed"),
                            VoteCount = 2
                        },
                        new
                        {
                            Id = new Guid("92569ac9-88c2-4be8-b160-11987226e24f"),
                            ConstituencyId = new Guid("db23f0a0-5ea0-450a-8d25-6afe3a8db280"),
                            Name = "candidate 3",
                            PartyId = new Guid("27c07a71-c70d-4528-b747-7cbbd06f059f"),
                            VoteCount = 1
                        },
                        new
                        {
                            Id = new Guid("a6b6e9c6-3e43-4da8-bf70-072ef8b2da75"),
                            ConstituencyId = new Guid("0ee8e91a-adb2-4909-952c-356afe9676fa"),
                            Name = "candidate 1",
                            PartyId = new Guid("22e5f6ea-ee2f-40d5-99ce-f48a18b87b95"),
                            VoteCount = 4
                        },
                        new
                        {
                            Id = new Guid("91b61aa7-b3bc-4e73-84a9-9fc3d98c2b10"),
                            ConstituencyId = new Guid("0ee8e91a-adb2-4909-952c-356afe9676fa"),
                            Name = "candidate 2",
                            PartyId = new Guid("dbb4d60a-e99d-4ea0-9451-c545266db2ed"),
                            VoteCount = 3
                        },
                        new
                        {
                            Id = new Guid("4d80bcc6-f567-4ad9-8a30-8fff6283fac9"),
                            ConstituencyId = new Guid("0ee8e91a-adb2-4909-952c-356afe9676fa"),
                            Name = "candidate 3",
                            PartyId = new Guid("27c07a71-c70d-4528-b747-7cbbd06f059f"),
                            VoteCount = 1
                        },
                        new
                        {
                            Id = new Guid("4eb4e16f-a66a-4d42-95d7-ca72e5f0d41e"),
                            ConstituencyId = new Guid("ae29b11a-f3ba-44e6-a73a-21a50c76681e"),
                            Name = "candidate 1",
                            PartyId = new Guid("a9c00507-f3d6-4fa8-ade9-ee6a437e6f25"),
                            VoteCount = 5
                        },
                        new
                        {
                            Id = new Guid("d4750984-c19d-4d73-86f1-6b9df66e523b"),
                            ConstituencyId = new Guid("ae29b11a-f3ba-44e6-a73a-21a50c76681e"),
                            Name = "candidate 2",
                            PartyId = new Guid("dbb4d60a-e99d-4ea0-9451-c545266db2ed"),
                            VoteCount = 2
                        },
                        new
                        {
                            Id = new Guid("4fddcd7e-18eb-40d6-90e5-554bfbb97347"),
                            ConstituencyId = new Guid("ae29b11a-f3ba-44e6-a73a-21a50c76681e"),
                            Name = "candidate 3",
                            PartyId = new Guid("27c07a71-c70d-4528-b747-7cbbd06f059f"),
                            VoteCount = 1
                        },
                        new
                        {
                            Id = new Guid("0a46b8a3-2d52-410a-876a-f5884a10c432"),
                            ConstituencyId = new Guid("02c9bafd-4bec-4235-ab57-b477a0dd21d9"),
                            Name = "candidate 1",
                            PartyId = new Guid("22e5f6ea-ee2f-40d5-99ce-f48a18b87b95"),
                            VoteCount = 2
                        },
                        new
                        {
                            Id = new Guid("f778f1bc-c443-4eed-a575-ec4ba54c3ed8"),
                            ConstituencyId = new Guid("02c9bafd-4bec-4235-ab57-b477a0dd21d9"),
                            Name = "candidate 2",
                            PartyId = new Guid("dbb4d60a-e99d-4ea0-9451-c545266db2ed"),
                            VoteCount = 10
                        },
                        new
                        {
                            Id = new Guid("055fb345-5db1-472d-9e02-ea099b5070f5"),
                            ConstituencyId = new Guid("02c9bafd-4bec-4235-ab57-b477a0dd21d9"),
                            Name = "candidate 3",
                            PartyId = new Guid("27c07a71-c70d-4528-b747-7cbbd06f059f"),
                            VoteCount = 1
                        },
                        new
                        {
                            Id = new Guid("7e8022a1-c0e3-4a97-af16-0c88ccd9855a"),
                            ConstituencyId = new Guid("014b152b-3088-402b-a725-83dbf6d467de"),
                            Name = "candidate 1",
                            PartyId = new Guid("22e5f6ea-ee2f-40d5-99ce-f48a18b87b95"),
                            VoteCount = 2
                        },
                        new
                        {
                            Id = new Guid("1a654501-bf89-42ff-af9c-369487b9b7cb"),
                            ConstituencyId = new Guid("014b152b-3088-402b-a725-83dbf6d467de"),
                            Name = "candidate 2",
                            PartyId = new Guid("dbb4d60a-e99d-4ea0-9451-c545266db2ed"),
                            VoteCount = 10
                        },
                        new
                        {
                            Id = new Guid("2368d93e-a8d9-4ecb-b459-104f0b0492bf"),
                            ConstituencyId = new Guid("014b152b-3088-402b-a725-83dbf6d467de"),
                            Name = "candidate 3",
                            PartyId = new Guid("27c07a71-c70d-4528-b747-7cbbd06f059f"),
                            VoteCount = 6
                        });
                });

            modelBuilder.Entity("gevs_api.Domain.CandidateResult", b =>
                {
                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Party")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Vote")
                        .HasColumnType("integer");

                    b.ToTable("CandidateResults");
                });

            modelBuilder.Entity("gevs_api.Domain.Constituency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Constituencies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0ee8e91a-adb2-4909-952c-356afe9676fa"),
                            Name = "Shangri-la-Town"
                        },
                        new
                        {
                            Id = new Guid("db23f0a0-5ea0-450a-8d25-6afe3a8db280"),
                            Name = "Northern-Kunlun-Mountain"
                        },
                        new
                        {
                            Id = new Guid("ae29b11a-f3ba-44e6-a73a-21a50c76681e"),
                            Name = "Western-Shangri-la"
                        },
                        new
                        {
                            Id = new Guid("02c9bafd-4bec-4235-ab57-b477a0dd21d9"),
                            Name = "Naboo-Vallery"
                        },
                        new
                        {
                            Id = new Guid("014b152b-3088-402b-a725-83dbf6d467de"),
                            Name = "New-Felucia"
                        });
                });

            modelBuilder.Entity("gevs_api.Domain.Election", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ongoing")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Elections");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b277ea66-7d91-4978-b21b-b492d416e8f0"),
                            Ongoing = false
                        });
                });

            modelBuilder.Entity("gevs_api.Domain.Party", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Parties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22e5f6ea-ee2f-40d5-99ce-f48a18b87b95"),
                            Name = "Red Party"
                        },
                        new
                        {
                            Id = new Guid("dbb4d60a-e99d-4ea0-9451-c545266db2ed"),
                            Name = "Blue Party"
                        },
                        new
                        {
                            Id = new Guid("27c07a71-c70d-4528-b747-7cbbd06f059f"),
                            Name = "Yellow Party"
                        },
                        new
                        {
                            Id = new Guid("a9c00507-f3d6-4fa8-ade9-ee6a437e6f25"),
                            Name = "Independent"
                        });
                });

            modelBuilder.Entity("gevs_api.Domain.VoteHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<bool>("HasVoted")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("VoteHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
