// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using gevs_api.Data;

#nullable disable

namespace gevs_api.Core.Migrations
{
    [DbContext(typeof(GevsDbContext))]
    partial class GevsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("gevs_api.Domain.Candidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConstituencyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("uuid");

                    b.Property<int>("VoteCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Candidates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4fa406d0-2c8e-4421-abf7-f97060ff191f"),
                            ConstituencyId = new Guid("f4723331-b57a-4a0d-9f53-8f99308b224a"),
                            Name = "candidate 1",
                            PartyId = new Guid("893bb9b4-a7d0-4f2d-ab51-5c20926540b5"),
                            VoteCount = 4
                        },
                        new
                        {
                            Id = new Guid("a45caa6d-89da-4ec5-980a-e34f3273e889"),
                            ConstituencyId = new Guid("f4723331-b57a-4a0d-9f53-8f99308b224a"),
                            Name = "candidate 2",
                            PartyId = new Guid("937ecdb8-c1c6-4de6-a3a0-545fc0851427"),
                            VoteCount = 2
                        },
                        new
                        {
                            Id = new Guid("af8be576-23e6-4b1d-86ce-e3dc72412f71"),
                            ConstituencyId = new Guid("f4723331-b57a-4a0d-9f53-8f99308b224a"),
                            Name = "candidate 3",
                            PartyId = new Guid("7255eb5a-7b60-47ff-a5a8-557989fb3dc5"),
                            VoteCount = 1
                        },
                        new
                        {
                            Id = new Guid("ee9ff9a3-2595-4e4e-9956-4acab4e0a5de"),
                            ConstituencyId = new Guid("1f9c33e1-9793-4bf2-948e-1a31d1344d42"),
                            Name = "candidate 1",
                            PartyId = new Guid("893bb9b4-a7d0-4f2d-ab51-5c20926540b5"),
                            VoteCount = 4
                        },
                        new
                        {
                            Id = new Guid("9294aa06-f73c-4005-8cfb-0d976aa5085a"),
                            ConstituencyId = new Guid("1f9c33e1-9793-4bf2-948e-1a31d1344d42"),
                            Name = "candidate 2",
                            PartyId = new Guid("937ecdb8-c1c6-4de6-a3a0-545fc0851427"),
                            VoteCount = 2
                        },
                        new
                        {
                            Id = new Guid("7433e71a-f895-4e20-b609-582b5acd2a64"),
                            ConstituencyId = new Guid("1f9c33e1-9793-4bf2-948e-1a31d1344d42"),
                            Name = "candidate 3",
                            PartyId = new Guid("7255eb5a-7b60-47ff-a5a8-557989fb3dc5"),
                            VoteCount = 1
                        },
                        new
                        {
                            Id = new Guid("953c2d2f-0536-4117-acf4-8a3f81586454"),
                            ConstituencyId = new Guid("90d0c297-68a5-4f3a-9de9-4d459c008a21"),
                            Name = "candidate 1",
                            PartyId = new Guid("e9188345-4789-43b0-a185-eaa19dccda36"),
                            VoteCount = 0
                        },
                        new
                        {
                            Id = new Guid("9e3cf705-f0bd-410f-9830-ac7ef38efac1"),
                            ConstituencyId = new Guid("90d0c297-68a5-4f3a-9de9-4d459c008a21"),
                            Name = "candidate 2",
                            PartyId = new Guid("937ecdb8-c1c6-4de6-a3a0-545fc0851427"),
                            VoteCount = 4
                        },
                        new
                        {
                            Id = new Guid("589c21f2-6191-4f16-a9bf-f72899b455b7"),
                            ConstituencyId = new Guid("90d0c297-68a5-4f3a-9de9-4d459c008a21"),
                            Name = "candidate 3",
                            PartyId = new Guid("893bb9b4-a7d0-4f2d-ab51-5c20926540b5"),
                            VoteCount = 2
                        },
                        new
                        {
                            Id = new Guid("d0c1238f-fc75-49d4-b36a-8fd502ac642d"),
                            ConstituencyId = new Guid("1dc37ad0-4e86-4202-8c41-db8abde152a6"),
                            Name = "candidate 1",
                            PartyId = new Guid("893bb9b4-a7d0-4f2d-ab51-5c20926540b5"),
                            VoteCount = 3
                        },
                        new
                        {
                            Id = new Guid("8c8e0376-0a84-4a98-8f8a-a667aa607141"),
                            ConstituencyId = new Guid("1dc37ad0-4e86-4202-8c41-db8abde152a6"),
                            Name = "candidate 2",
                            PartyId = new Guid("937ecdb8-c1c6-4de6-a3a0-545fc0851427"),
                            VoteCount = 0
                        },
                        new
                        {
                            Id = new Guid("db0ba7bd-a0c5-4c1e-bb4b-c4cb047fc3ea"),
                            ConstituencyId = new Guid("1dc37ad0-4e86-4202-8c41-db8abde152a6"),
                            Name = "candidate 3",
                            PartyId = new Guid("7255eb5a-7b60-47ff-a5a8-557989fb3dc5"),
                            VoteCount = 1
                        },
                        new
                        {
                            Id = new Guid("096941a7-9287-49bc-b856-ef212a2bd6b0"),
                            ConstituencyId = new Guid("b15ba89f-7119-419a-a9ef-1d0324970eb6"),
                            Name = "candidate 1",
                            PartyId = new Guid("893bb9b4-a7d0-4f2d-ab51-5c20926540b5"),
                            VoteCount = 2
                        },
                        new
                        {
                            Id = new Guid("0ca537c5-3a31-4a22-ab07-92cd219646cd"),
                            ConstituencyId = new Guid("b15ba89f-7119-419a-a9ef-1d0324970eb6"),
                            Name = "candidate 2",
                            PartyId = new Guid("937ecdb8-c1c6-4de6-a3a0-545fc0851427"),
                            VoteCount = 0
                        },
                        new
                        {
                            Id = new Guid("0da8fdad-980a-43a9-a07e-1d12a149f51f"),
                            ConstituencyId = new Guid("b15ba89f-7119-419a-a9ef-1d0324970eb6"),
                            Name = "candidate 3",
                            PartyId = new Guid("7255eb5a-7b60-47ff-a5a8-557989fb3dc5"),
                            VoteCount = 6
                        });
                });

            modelBuilder.Entity("gevs_api.Domain.Constituency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Constituencies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1f9c33e1-9793-4bf2-948e-1a31d1344d42"),
                            Name = "Shangri-la-Town"
                        },
                        new
                        {
                            Id = new Guid("f4723331-b57a-4a0d-9f53-8f99308b224a"),
                            Name = "Northern-Kunlun-Mountain"
                        },
                        new
                        {
                            Id = new Guid("90d0c297-68a5-4f3a-9de9-4d459c008a21"),
                            Name = "Western-Shangri-la"
                        },
                        new
                        {
                            Id = new Guid("1dc37ad0-4e86-4202-8c41-db8abde152a6"),
                            Name = "Naboo-Vallery"
                        },
                        new
                        {
                            Id = new Guid("b15ba89f-7119-419a-a9ef-1d0324970eb6"),
                            Name = "New-Felucia"
                        });
                });

            modelBuilder.Entity("gevs_api.Domain.Election", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ongoing")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Elections");

                    b.HasData(
                        new
                        {
                            Id = new Guid("446ad0ad-5eba-4479-92c8-45e2d45340e8"),
                            Ongoing = false
                        });
                });

            modelBuilder.Entity("gevs_api.Domain.Party", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Parties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("893bb9b4-a7d0-4f2d-ab51-5c20926540b5"),
                            Name = "Red Party"
                        },
                        new
                        {
                            Id = new Guid("937ecdb8-c1c6-4de6-a3a0-545fc0851427"),
                            Name = "Blue Party"
                        },
                        new
                        {
                            Id = new Guid("7255eb5a-7b60-47ff-a5a8-557989fb3dc5"),
                            Name = "Yellow Party"
                        },
                        new
                        {
                            Id = new Guid("e9188345-4789-43b0-a185-eaa19dccda36"),
                            Name = "Independent"
                        });
                });

            modelBuilder.Entity("gevs_api.Domain.VoteHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<bool>("HasVoted")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("VoteHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
